"""Herf Sehvi

Revision ID: 5f5964bb2d5c
Revises: e95a0da1328a
Create Date: 2021-03-14 17:24:59.044453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5964bb2d5c'
down_revision = 'e95a0da1328a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Eduhistory', sa.Column('enddate', sa.String(length=30), nullable=True))
    op.drop_column('Eduhistory', 'endtdate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Eduhistory', sa.Column('endtdate', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('Eduhistory', 'enddate')
    # ### end Alembic commands ###
