"""Sakawsd

Revision ID: 7d9166befa6c
Revises: 858648951d8b
Create Date: 2021-03-26 00:39:49.653977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9166befa6c'
down_revision = '858648951d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('percatage', sa.String(length=120), nullable=True),
    sa.Column('skill_catagory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_catagory'], ['SkillCatagory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Skills')
    # ### end Alembic commands ###
