"""Sakaw

Revision ID: 858648951d8b
Revises: df9fa2934f96
Create Date: 2021-03-26 00:36:47.865954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858648951d8b'
down_revision = 'df9fa2934f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SkillCatagory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SkillCatagory')
    # ### end Alembic commands ###
