"""Saka

Revision ID: df9fa2934f96
Revises: 
Create Date: 2021-03-25 18:31:56.589884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9fa2934f96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profileimg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Profileimg')
    # ### end Alembic commands ###
