"""EduHistory

Revision ID: e95a0da1328a
Revises: 
Create Date: 2021-03-14 16:25:41.286497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95a0da1328a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Eduhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('startdate', sa.String(length=30), nullable=True),
    sa.Column('endtdate', sa.String(length=30), nullable=True),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Eduhistory')
    # ### end Alembic commands ###
